[package]
name = "Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
ev3dev-lang-rust = { version = "0.14", features = ["ev3", "screen"] }

[profile.release]
lto = true
strip = true
opt-level = "s"